tarantool/memcached

memcached/internal/mc_sasl.c
memcached/internal/mc_sasl.h
memcached/internal/memcached.c

Should close tarantool/tarantool#3392

Add forgotten connection context disposal for SASL

---

memcached/init.lua
memcached/internal/expiration.c

Checking box.error.last() is the only way to determine that fiber start was failed.
Also another way to find `internal.so`
Checked on 1.10.
Closes #44.

Error on expiration fiber start while under tarantoolctl

---

memcached/init.lua
memcached/internal/memcached.c
memcached/internal/memcached.h
memcached/internal/memcached_layer.c
memcached/internal/proto_bin.c
memcached/internal/proto_txt.c
test/text/multiversioning.result
test/text/multiversioning.test.py

Before introducing a txn memory region box_txn_alloc() allocates memory using the fiber.gc region and can be used without box_txn_begin(). Now the similar trick doesn't work (a transaction must be started).
To allocate memory on region without start a transaction, the region was added to struct memcached_connection.
Fixes #53

Fix memory allocate during request processing

---

memcached/init.lua

If symbols from the dynamic library are loaded into the
global namespace (ffi.C), by invoke ffi.load() with global
is true and without save the return value, it may be
garbage collected. For correct work the return value
must be saved.
Example - https://github.com/tarantool/tarantool/issues/4999
So, use a new C library namespace instead the global one.
This will help to keep the global namespace clean and
avoid the problem with garbage collection.

ffi: use a new C library namespace when the dynamic library load

---

CMakeLists.txt

The "small" library version has been updated.
Part of #59

small: bump new version

---

.travis.yml
test.sh

Now, Travis CI will run tests for memcached module
using Tarantool versions 1.10, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7
Added few jobs to .travis.yml for this feature.
Updated way to enable tarantool repo to
`curl -L https://tarantool.io/installer.sh | sudo VER=2.5 bash`
in test.sh and made TARANTOOL_VERSION variable in test.sh
Closed #58

ci: verify on different tarantool versions

---

rpm/tarantool-memcached.spec

Update Tarantool version requirement to 1.10 along the way: see 702d673a7a61b4e3a46f756988d95e991c134711
Not sure about the libsmall discrepancies: please see #59 and #60

Update RPM spec to require recent Tarantool versions

---

debian/control

Follows up commit 1f6d7b03eae7555a0c3914888f5f526bc62ead31 ('Update RPM
spec file to match the rockspec').
Since tarantool-memcached-1.0.1 we support tarantool-1.10 or newer (see
the release notes [1]). This change reflects this fact in the Debian
packages for the module.
[1]: https://github.com/tarantool/memcached/releases/tag/1.0.1
@ChangeLog (for #68 and this PR both): Updated the RPM and Deb packages
to reflect the fact that the module supports tarantool since 1.10.

build: require tarantool-1.10+ in Debian packages

---

rockspecs/memcached-1.0.0-1.rockspec
rockspecs/memcached-1.0.1-1.rockspec
rockspecs/memcached-scm-1.rockspec

GitHub is going to disable unencrypted Git protocol, so `git://` URLs
will stop working soon (see [1]).
[1]: https://github.blog/2021-09-01-improving-git-protocol-security-github/
Part of https://github.com/tarantool/tarantool/issues/6587

rockspec: use git+https:// for git repository URL

---

.github/workflows/reusable_testing.yml
.github/workflows/testing.yaml

The idea of this workflow is to be a part of the 'integration.yml'
workflow from the tarantool repo to verify the integration of the
memcached module with an arbitrary tarantool version.
This workflow is not triggered on a push to the repo and cannot be run
manually since it has only the 'workflow_call' trigger. This workflow
will be included in the tarantool development cycle and called by the
'integration.yml' workflow from the tarantool project on a push to the
master and release branches for verifying integration of tarantool with
memcached.
Part of tarantool/tarantool#6563
Part of tarantool/tarantool#5265
Part of tarantool/tarantool#6056
Related to tarantool/tarantool#6613

github-ci: add reusable testing workflow

---

.github/workflows/reusable_testing.yml

This patch skips tests run for tarantool 2.10 in reusable_testing.yml
workflow due to the bug [1]. After [1] is fixed, the skip condition
should be removed from the workflow.
[1] https://github.com/tarantool/memcached/issues/96

github-ci: skip running tests for tarantool 2.10

---

test/bench/memtier.test.lua

Suppress output with DEVNULL instead of PIPE when test-run is used for
running benchmark and reflect test run status in exit code.
Follows up #81

test: fixes for memtier benchmark wrapper

---

.github/workflows/reusable_testing.yml

The memcached tests have migrated to Python 3 recently in scope of #82.
But reusable_testing.yml workflow wasn't updated and tests started to
fail. This patch fixes the issue.

ci: use python 3 in reusable_testing.yml workflow

---

memcached/init.lua

memcached shows unclear error when memcached instance created without box
initialization:
```
tarantool> mc = require('memcached')
tarantool> mc.create('instance', '127.0.0.1:8080', { proto = 'text'})
---
- error: '/home/sergeyb/sources/MRG/memcached/memcached/init.lua:111: attempt to index
field ''cfg'' (a function value)'
...
```
With patch memcached checks whether box is initialized or not and shows a
correct message:
```
tarantool> mc.create('instance', '127.0.0.1:8080', { proto = 'text'})
---
- error: '/home/sergeyb/sources/MRG/memcached/memcached/init.lua:344: Tarantool must
be initialized with box.cfg()'
...
```
Fixes #76

memcached: check tarantool's box before init

---

memcached/init.lua

For creating memcached instance module requires instance name, URI and
table with options. URI is a string with hostname and port number
separated by colon. Instead URI user can pass a port as a number, but
memcached doesn't expect it and fails with exception. Patch fixes it by
adding conversion of uri to a string.
Fixes #107

memcached: allow to pass port as a number to memcached.create()

---

memcached/init.lua

memcached: fix upper value for readahead parameter

---

HACKING.md
README.md
memcached/CMakeLists.txt
memcached/internal/memcached.c
memcached/internal/network.c
memcached/internal/network.h
memcached/internal/proto_bin.c
memcached/internal/proto_txt.c
third_party/memcached_ibuf.c
third_party/memcached_ibuf.h

Copy `ibuf.c` and `ibuf.h` from small into the module's code and rename the functions to `memcached_ibuf_*()`.
See https://github.com/tarantool/tarantool/issues/6873 for the root problem and https://github.com/tarantool/memcached/issues/59#issuecomment-1081106140 for analysis.
`ibuf_*()` symbols may clash with the same named symbols in tarantool, so it worth to rename them to avoid effects of different binary layouts: assertion fails and memory corruptions.
It is the last known problem from #59. All others are confirmed as safe to ignore if we'll keep current libsmall version in the module (see the issue).
More details can be found in the commit messages.
Fixes #59

ibuf: don't clash with tarantool's ibuf_*() symbols

---

.github/workflows/packaging.yml

"echo *" can function as "ls". The shell will expand the asterisk to whatever is in that directory. Therefore, it is necessary to escape this characters.

Fix the curl command print

---

.github/workflows/publish.yml

The problem is that on Ubuntu 22.04 luarocks v3 from the `tarantool-common` package is installed, but tarantoolctl from tarantool 1.10 uses luarocks v2.
See [1] for more details.
[1] https://github.com/tarantool/tarantool/issues/5429#issuecomment-1336162554

Fix rockspec publishing

---

test/binary/binary-boundary.test.py
test/binary/binary-expire.test.py
test/binary/binary-gh-73.test.py
test/binary/binary-toobig.test.py
test/binary/binary.lua
test/binary/binary.test.py
test/capable/capable-binary.test.py
test/capable/capable-text.test.py
test/capable/capable.lua
test/internal/memcached_connection.py
test/sasl/binary-sasl.test.py
test/text/binary-get.test.py
test/text/bogus-commands.test.py
test/text/cas.test.py
test/text/expirations.test.py
test/text/flags.test.py
test/text/flush-all.test.py
test/text/getset.test.py
test/text/incrdecr.test.py
test/text/multiversioning.test.py
test/text/noreply.test.py
test/text/text.lua

In the near future we plan to test Tarantool installed from a DEB/RPM package. Since 3.0.0-alpha1 release Tarantool packages don't have the tarantoolctl utility inside.
tarantoolctl was ebmed to the test-run project inself. The submodule has been updated to the latest version.
Part of tarantool/tarantool#9443

ci: bump test-run

---

memcached/internal/network.c

We are going to finish all client (non-system) fibers in the process of Tarantool shutdown. First we cancel them and then wait for their finishing. So if the client fibers are not finished Tarantool shutdown is never finished too.
Currently memcached service fiber can not be finished and we got hang on integration testing of PR [1]. Let's fix it.
[1] PR with client fibers finishing on shutdown.
https://github.com/tarantool/tarantool/pull/9604

memcached: make cancellable

---

.github/workflows/packaging.yml
CHANGELOG.md

Fedora 34 needs to be supported and wasn't included to the platform list, but `packpack/packpack` supports it.
After the patch this platform has been included.
Part of #128

ci: add fedora 34 platform to packaging

---

.github/workflows/check.yaml
.github/workflows/packaging.yml
rpm/prebuild.sh

Almalinux 8, 9 needs to be supported and wasn't included to the platform list, but `packpack/packpack` supports it.
After the patch this platform has been included.
Closes #128

ci: add almalinux platform to packaging
